[[apps]]
title = "Flatpak"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/flatpak/assets/icon.png"

[apps.runner]
type = "docker"
name = "WolfFlatpak"
image = "ghcr.io/games-on-whales/flatpak:edge"
env = [
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
    "FLATPAK_APP_ID=org.videolan.VLC"
]
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
